### PR TITLE
backward compatibility with PlayStore versions and new tests for the new PlayStore version

### PR DESCRIPTION
**Pull request by AdeilsonESilva**

### CODE REVIEW

**Review by Parth8733 — APPROVED** [review]

**Comment by sumit-anar** [comment]
@AdeilsonESilva can you please fix the test cases on priority?

**Comment by sumit-anar** [comment]
@Parth8733 these pipelines are failing in the current master as well. Can you please bypass these if it's not adding any tech debt?

**Comment by arelstone** [comment]
I really appreciate this PR.

Can we PLEASE have this PR fixed, merged and released

**Review by gokugen — APPROVED** [review]

**Comment by ng-parth** [comment]
Hello @gokugen  / @Parth8733,    
Is there any expected date to merge these changes and release a newer version of the npm package?

**Review by mshavandi — APPROVED** [review]

**Review by stefanleoussis — APPROVED** [review]

**Pull request merged**
